name: CI Tests

# # workflow dispatch requires a maintainer to go to the Actions tab and manually trigger the workflow
on:
  push:
    branches:
      - main
    paths:
      - "packages/accounts/src/**"
      - "packages/accounts/package.json"
      - "e2e-tests"
  workflow_dispatch:

# # If we ever migrate this to not be manual, we HAVE to check that the commit
# # it is running against DOES NOT contain [skip-ci] in the commit message
jobs:
  build_test:
    name: Build, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.13"
          cache: "yarn"

      - name: Install SDK dependencies
        run: yarn --frozen-lockfile

      - name: Build SDK
        run: yarn build

      - name: Link SDK
        run: yarn --cwd packages/accounts link

      - name: Install E2E tests
        run: yarn --cwd e2e-tests link @zerodev/sdk && yarn --cwd e2e-tests

      - name: E2E tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: yarn --cwd e2e-tests test:e2e
