name: Run checks on Pull Requests
on:
  pull_request:

jobs:
  enforce_title:
    name: Enforce PR Title Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.13"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Use commitlint to check PR title
        run: echo "${{ github.event.pull_request.title }}" | yarn commitlint

  build_and_lint_and_test:
    name: Lint and Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.13"
          cache: "yarn"

      - name: Install SDK dependencies
        run: yarn install --frozen-lockfile

      - name: Lint SDK
        run: yarn lint:check

      - name: Build SDK
        run: yarn build

      - name: Link SDK
        run: yarn --cwd packages/accounts link

      - name: Install E2E tests
        run: yarn --cwd e2e-tests link @zerodev/sdk && yarn --cwd e2e-tests

      - name: E2E tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: yarn --cwd e2e-tests test:e2e
